sudo: required

services:
  - docker

language: python

python:
  - '3.7'

install:
  - pip install -e .[tests]

script:
  - pytest

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/5d585e560cb2e7b4fe45
    on_success: change
    on_failure: always
    on_start: never
