sudo: required

services:
  - docker

before_install:
  - docker build --tag tensortrade -f docker/Dockerfile.tests .

script: docker run \
  --user $(id -u):$(id -g) \
  --interactive \
  --tty \
  --volume "${CWD}":/code \
  "$N" \
  python -m pytest -p no:warnings /code/test

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/5d585e560cb2e7b4fe45
    on_success: change # options: [always|never|change] default: always
    on_failure: always # options: [always|never|change] default: always
    on_start: never # options: [always|never|change] default: always
